services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: inventory_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
    ports:
      - "5435:5432"
    volumes:
      - postgres_inventory_service:/var/lib/postgresql/data

volumes:
  postgres_inventory_service: